# frozen_string_literal: true

require "ostruct"
require "json"

module AssemblyAI
  class Lemur
    # An answer generated by LeMUR and its question
    class LemurQuestionAnswer
      # @return [String] The question for LeMUR to answer
      attr_reader :question
      # @return [String] The answer generated by LeMUR
      attr_reader :answer
      # @return [OpenStruct] Additional properties unmapped to the current class definition
      attr_reader :additional_properties
      # @return [Object]
      attr_reader :_field_set
      protected :_field_set

      OMIT = Object.new

      # @param question [String] The question for LeMUR to answer
      # @param answer [String] The answer generated by LeMUR
      # @param additional_properties [OpenStruct] Additional properties unmapped to the current class definition
      # @return [AssemblyAI::Lemur::LemurQuestionAnswer]
      def initialize(question:, answer:, additional_properties: nil)
        @question = question
        @answer = answer
        @additional_properties = additional_properties
        @_field_set = { "question": question, "answer": answer }
      end

      # Deserialize a JSON object to an instance of LemurQuestionAnswer
      #
      # @param json_object [String]
      # @return [AssemblyAI::Lemur::LemurQuestionAnswer]
      def self.from_json(json_object:)
        struct = JSON.parse(json_object, object_class: OpenStruct)
        parsed_json = JSON.parse(json_object)
        question = parsed_json["question"]
        answer = parsed_json["answer"]
        new(
          question: question,
          answer: answer,
          additional_properties: struct
        )
      end

      # Serialize an instance of LemurQuestionAnswer to a JSON object
      #
      # @return [String]
      def to_json(*_args)
        @_field_set&.to_json
      end

      # Leveraged for Union-type generation, validate_raw attempts to parse the given
      #  hash and check each fields type against the current object's property
      #  definitions.
      #
      # @param obj [Object]
      # @return [Void]
      def self.validate_raw(obj:)
        obj.question.is_a?(String) != false || raise("Passed value for field obj.question is not the expected type, validation failed.")
        obj.answer.is_a?(String) != false || raise("Passed value for field obj.answer is not the expected type, validation failed.")
      end
    end
  end
end
