name: CI

on: [ push ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - run: bundle install

      - name: Rubocop
        run: bundle exec rubocop

      - name: Test
        run: bundle exec ruby test/test_assemblyai.rb
